name: Proyectos digitales
markdown: redcarpet
base-url: /
timezone: Europe/Berlin


# prose options
prose:
  rooturl: "_posts"
  siteurl: "http://editio.github.io/"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "author"
        field:
          element: "text"
          label: "author"
          placeholder: "your name"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "title"
          placeholder: "post title"
          value: ""
    
